### ISSUE TITLE
User Story; Edit, delete and update products via GUI

### ISSUE THREAD

**Issue by chrissuttondev** [chrissuttondev/William-George-Retail#18]
As a site admin, I would like to **add/remove/edit products in the store via the a secure area of the website** to enable me to easily manage the product inventory.**

Acceptance Criteria

The admin panel should have accessible options to add, remove, and edit products.

Admin actions (add, remove, edit) should be confirmed with a success message.

Only authenticated admins should access the product management features.

## Tasks

- [ ] Create forms for adding, removing, and editing products.
- [ ] Ensure working functionality to save new products, product updates and  to remove deletions to / from the database.
- [ ] Display a success message upon successful product addition/update/deletion.
- [ ] Add a warning message  and confirmation step to guard against products being updated/added/deleted by mistake.
